#!/bin/bash
# Enterprise KB PoC — One-click Azure deployment
#
# Prerequisites:
#   1. Azure CLI installed: brew install azure-cli
#   2. Logged in: az login
#   3. Subscription selected: az account set -s <subscription-id>
#
# Usage:
#   ./deploy/deploy.sh          # Deploy all resources
#   ./deploy/deploy.sh teardown # Delete everything
#
# Cost: < $1 if torn down within 1-2 hours

set -euo pipefail

RESOURCE_GROUP="ekb-poc-rg"
LOCATION="eastasia"
PREFIX="ekb-poc"
BICEP_FILE="deploy/main.bicep"
ENV_FILE=".env"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[deploy]${NC} $1"; }
ok()  { echo -e "${GREEN}[  ok  ]${NC} $1"; }
err() { echo -e "${RED}[error]${NC} $1"; }

# ============================================================
# Teardown
# ============================================================
if [ "${1:-}" = "teardown" ]; then
    log "Deleting resource group: $RESOURCE_GROUP"
    echo ""
    echo "This will permanently delete ALL resources in the group."
    read -p "Are you sure? (y/N) " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        az group delete --name "$RESOURCE_GROUP" --yes --no-wait
        ok "Resource group deletion initiated (runs in background)"
        echo ""
        echo "Resources will be fully deleted in 2-5 minutes."
        echo "Verify: az group show --name $RESOURCE_GROUP 2>&1 | head -1"
        # Clean up local .env
        if [ -f "$ENV_FILE" ]; then
            rm "$ENV_FILE"
            ok "Removed local .env file"
        fi
    else
        log "Cancelled."
    fi
    exit 0
fi

# ============================================================
# Pre-flight checks
# ============================================================
log "Pre-flight checks..."

if ! command -v az &> /dev/null; then
    err "Azure CLI not found. Install: brew install azure-cli"
    exit 1
fi

# Check login
if ! az account show &> /dev/null; then
    err "Not logged in. Run: az login"
    exit 1
fi

ACCOUNT=$(az account show --query '{name:name, id:id}' -o tsv)
ok "Logged in: $ACCOUNT"

# Check if OpenAI is available in the region
log "Checking Azure OpenAI availability in $LOCATION..."
# Azure OpenAI might not be available in all regions
# eastasia usually has GPT-4o and embeddings

# ============================================================
# Deploy
# ============================================================
log "Creating resource group: $RESOURCE_GROUP in $LOCATION"
az group create --name "$RESOURCE_GROUP" --location "$LOCATION" -o none
ok "Resource group created"

log "Deploying Azure resources (AI Search + OpenAI + Cosmos DB)..."
log "This takes 2-5 minutes..."
echo ""

DEPLOYMENT_OUTPUT=$(az deployment group create \
    --resource-group "$RESOURCE_GROUP" \
    --template-file "$BICEP_FILE" \
    --parameters prefix="$PREFIX" location="$LOCATION" \
    --query 'properties.outputs' \
    -o json)

ok "Deployment complete!"

# ============================================================
# Extract outputs and create .env
# ============================================================
log "Extracting connection details..."

SEARCH_NAME=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['searchServiceName']['value'])")
SEARCH_KEY=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['searchAdminKey']['value'])")
OPENAI_ENDPOINT=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['openaiEndpoint']['value'])")
OPENAI_KEY=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['openaiKey']['value'])")
COSMOS_ENDPOINT=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['cosmosEndpoint']['value'])")
COSMOS_KEY=$(echo "$DEPLOYMENT_OUTPUT" | python3 -c "import sys,json; print(json.load(sys.stdin)['cosmosKey']['value'])")

cat > "$ENV_FILE" << EOF
# Azure deployment — generated by deploy.sh
# DELETE THIS FILE after testing (contains secrets)

# Azure OpenAI
AZURE_OPENAI_ENDPOINT=$OPENAI_ENDPOINT
AZURE_OPENAI_API_KEY=$OPENAI_KEY
AZURE_OPENAI_API_VERSION=2024-10-21

# Azure AI Search
AZURE_SEARCH_ENDPOINT=https://${SEARCH_NAME}.search.windows.net
AZURE_SEARCH_KEY=$SEARCH_KEY

# Azure Cosmos DB
AZURE_COSMOS_ENDPOINT=$COSMOS_ENDPOINT
AZURE_COSMOS_KEY=$COSMOS_KEY

# Models (deployed on Azure OpenAI)
EMBEDDING_MODEL=text-embedding-3-large
CHAT_MODEL=gpt-4o
EOF

ok "Created .env with all connection details"

# ============================================================
# Summary
# ============================================================
echo ""
echo "=========================================="
echo "  Deployment Complete"
echo "=========================================="
echo ""
echo "Resources deployed in: $RESOURCE_GROUP"
echo "  - Azure AI Search (Free):  https://${SEARCH_NAME}.search.windows.net"
echo "  - Azure OpenAI:            $OPENAI_ENDPOINT"
echo "  - Cosmos DB:               $COSMOS_ENDPOINT"
echo ""
echo "Next steps:"
echo "  1. pip install azure-search-documents azure-cosmos  # Install Azure SDKs"
echo "  2. python deploy/migrate.py                         # Upload data to Azure"
echo "  3. python deploy/test_azure.py                      # Run E2E test on Azure"
echo ""
echo "When done testing:"
echo "  ./deploy/deploy.sh teardown                         # Delete ALL resources"
echo ""
echo "⚠  IMPORTANT: Tear down when done to avoid charges!"
echo ""
